### ISSUE TITLE
Add Support from the backend

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-drops-chrome-extension#1]
@julianpoy I would appreciate if you would look over my xhttp json post requests.

Basically, I figured we could give every account a sessiontoken on creation called the extension code, that doesnt expire and they could grab from the my account page. and then on the extension options,they can place the code in their settings, and then allows us to post urls with their extension code. the code is all there for this, just needs some polishing

**Comment by torch2424** [comment]
I think another alternative is to just make a dumps/extension route, and then make it so that we can submit dumps through user id

**Comment by julianpoy** [comment]
Thats generally a very bad Idea. There should be no need for that. Ill look into this later this evening when I'm coding while Alexis practices

**Comment by torch2424** [comment]
Ayyyeee you down to let me tag along?

**Comment by torch2424** [comment]
FInshed via 27f86887a0abcbf5d363e8cc3420edeac077e2c3

**Comment by torch2424** [comment]
for some random development I'm doing, I dont want to creat an apple id to download hangouts. Here's the url I need

http://front.ngrok.kondeo.com:8080/#/giftcards/create?token=1fb159291e4d85fda41c648c73aa3147b150e0e5eb29a45c630a98059d24ca2a5236c67eb728538ea7cf67b692352b43

**Comment by julianpoy** [comment]
Huh? This is in link-drops...
